INSERT INTO packing_items (category, item, packed) VALUES
-- Pilgrimage items
('Pilgrimage', 'Stamp book (nokyocho)', 0),
('Pilgrimage', 'White vest (hakui)', 0),
('Pilgrimage', 'Sedge hat (kasa)', 0),
('Pilgrimage', 'Walking staff (kongozue)', 0),
('Pilgrimage', 'Rosary beads (juzu)', 0),
('Pilgrimage', 'Incense sticks', 0),
('Pilgrimage', 'Candles', 0),
('Pilgrimage', 'Coin purse for offerings', 0),
('Pilgrimage', 'Name slips (osamefuda)', 0),
('Pilgrimage', 'Heart Sutra booklet', 0),
-- Clothing
('Clothing', 'Moisture-wicking base layer tops (x3)', 0),
('Clothing', 'Walking trousers (x2)', 0),
('Clothing', 'Warm mid layer / fleece', 0),
('Clothing', 'Rain jacket', 0),
('Clothing', 'Rain trousers', 0),
('Clothing', 'Merino wool socks (x5)', 0),
('Clothing', 'Underwear (x4)', 0),
('Clothing', 'Light gloves', 0),
('Clothing', 'Buff / neck gaiter', 0),
('Clothing', 'Warm hat', 0),
('Clothing', 'Sandals / camp shoes', 0),
('Clothing', 'Walking shoes or trail runners', 0),
-- Gear
('Gear', 'Backpack (40-50L)', 0),
('Gear', 'Backpack rain cover', 0),
('Gear', 'Sleeping bag liner', 0),
('Gear', 'Trekking poles', 0),
('Gear', 'Headlamp + spare batteries', 0),
('Gear', 'Dry bags / pack liners', 0),
('Gear', 'Water bottle (1L minimum)', 0),
('Gear', 'Microfibre towel', 0),
('Gear', 'Packable daypack', 0),
('Gear', 'Gaiters', 0),
-- Medicine
('Medicine', 'Blister plasters (Compeed)', 0),
('Medicine', 'Athletic tape', 0),
('Medicine', 'Ibuprofen', 0),
('Medicine', 'Antidiarrheal tablets', 0),
('Medicine', 'Antihistamine', 0),
('Medicine', 'Muscle pain cream', 0),
('Medicine', 'Sunscreen', 0),
('Medicine', 'Insect repellent', 0),
('Medicine', 'Prescription medications', 0),
('Medicine', 'Small first aid kit', 0),
-- Electronics
('Electronics', 'Phone', 0),
('Electronics', 'Portable charger (power bank)', 0),
('Electronics', 'Universal travel adapter', 0),
('Electronics', 'Charging cables', 0),
('Electronics', 'Earphones', 0),
('Electronics', 'Waterproof phone case', 0),
-- Documents
('Documents', 'Passport', 0),
('Documents', 'Travel insurance documents', 0),
('Documents', 'Japan Rail Pass (if applicable)', 0),
('Documents', 'Emergency contact card', 0),
('Documents', 'Accommodation bookings', 0),
('Documents', 'Cash (yen) — many temples are cash only', 0),
-- Other
('Other', 'Laundry detergent sheets', 0),
('Other', 'Earplugs (for shared dorms)', 0),
('Other', 'Lightweight notebook + pen', 0),
('Other', 'Snacks for long mountain stretches', 0),
('Other', 'Lip balm', 0),
('Other', 'Hand sanitiser', 0);