INSERT OR IGNORE INTO temples (number, name_en, name_jp, location, prefecture, km_from_previous, deity, address, image_url) VALUES
(1, 'Ryozen-ji', '霊山寺', 'Naruto', 'Tokushima', 0, 'Shakyamuni Buddha', '126 Bandoji, Naruto, Tokushima 779-0230', 'https://commons.wikimedia.org/wiki/File:Ryozenji01.jpg'),
(2, 'Gokuraku-ji', '極楽寺', 'Naruto', 'Tokushima', 1.4, 'Amida Nyorai', '12 Gokurakuji, Naruto, Tokushima 779-0225', 'https://commons.wikimedia.org/wiki/File:Gokurakuji_Naruto.jpg'),
(3, 'Konsen-ji', '金泉寺', 'Itano', 'Tokushima', 2.6, 'Shakyamuni Buddha', '276 Kokufu, Itano, Tokushima 779-0113', 'https://commons.wikimedia.org/wiki/File:Konsenji01.jpg'),
(4, 'Dainichi-ji', '大日寺', 'Itano', 'Tokushima', 5.0, 'Dainichi Nyorai', '61-2 Kuramoto, Itano, Tokushima 779-0108', 'https://commons.wikimedia.org/wiki/File:Dainichiji_Itano.jpg'),
(5, 'Jizo-ji', '地蔵寺', 'Itano', 'Tokushima', 2.0, 'Kshitigarbha', '887 Komatsushima, Itano, Tokushima 779-0105', 'https://commons.wikimedia.org/wiki/File:Jizoji01.jpg'),
(6, 'Anraku-ji', '安楽寺', 'Kamiita', 'Tokushima', 9.6, 'Yakushi Nyorai', '1 Jodoji, Kamiita, Tokushima 771-1506', 'https://commons.wikimedia.org/wiki/File:Anrakuji_Kamiita.jpg'),
(7, 'Jurin-ji', '十楽寺', 'Awa', 'Tokushima', 1.3, 'Amida Nyorai', '1-4 Sakaguchi, Awa, Tokushima 771-1509', 'https://commons.wikimedia.org/wiki/File:Jurinjii01.jpg'),
(8, 'Kumadani-ji', '熊谷寺', 'Awa', 'Tokushima', 4.4, 'Senju Kannon', 'Gorogoro, Awa, Tokushima 771-1505', 'https://commons.wikimedia.org/wiki/File:Kumadaniji01.jpg'),
(9, 'Horin-ji', '法輪寺', 'Awa', 'Tokushima', 5.0, 'Nizen Kannon', 'Dobashi, Awa, Tokushima 771-1506', 'https://commons.wikimedia.org/wiki/File:Horinji_Awa.jpg'),
(10, 'Kirihata-ji', '切幡寺', 'Awa', 'Tokushima', 3.5, 'Senju Kannon', 'Kirihata, Awa, Tokushima 771-1623', 'https://commons.wikimedia.org/wiki/File:Kirihataji01.jpg'),
(11, 'Fujii-dera', '藤井寺', 'Yoshinogawa', 'Tokushima', 9.0, 'Yakushi Nyorai', 'Fujii, Yoshinogawa, Tokushima 776-0010', 'https://commons.wikimedia.org/wiki/File:Fujiiidera01.jpg'),
(12, 'Shosan-ji', '焼山寺', 'Kamiyama', 'Tokushima', 16.0, 'Kokuzo Bosatsu', 'Kawai, Kamiyama, Tokushima 771-3310', 'https://commons.wikimedia.org/wiki/File:Shosanji01.jpg'),
(13, 'Dainichi-ji', '大日寺', 'Tokushima', 'Tokushima', 22.0, 'Juichimen Kannon', '1084 Jodoji, Tokushima 779-3140', 'https://commons.wikimedia.org/wiki/File:Dainichiji_Tokushima.jpg'),
(14, 'Joraku-ji', '常楽寺', 'Tokushima', 'Tokushima', 2.8, 'Miroku Bosatsu', '126 Tokushimamachi, Tokushima 779-3131', 'https://commons.wikimedia.org/wiki/File:Jorakuji01.jpg'),
(15, 'Kokubun-ji', '国分寺', 'Tokushima', 'Tokushima', 3.5, 'Miroku Bosatsu', '80 Kokufucho, Tokushima 779-3133', 'https://commons.wikimedia.org/wiki/File:Kokubunji_Tokushima.jpg'),
(16, 'Kannonji', '観音寺', 'Tokushima', 'Tokushima', 1.5, 'Senju Kannon', '102 Hommachi, Tokushima 779-3134', 'https://commons.wikimedia.org/wiki/File:Kannonji_Tokushima.jpg'),
(17, 'Ido-ji', '井戸寺', 'Tokushima', 'Tokushima', 2.5, 'Shichimen Kannon', '80-1 Ichinomiyacho, Tokushima 779-3120', 'https://commons.wikimedia.org/wiki/File:Idoji01.jpg'),
(18, 'Onzan-ji', '恩山寺', 'Komatsushima', 'Tokushima', 13.0, 'Miroku Bosatsu', 'Tera, Komatsushima, Tokushima 773-0017', 'https://commons.wikimedia.org/wiki/File:Onzanji01.jpg'),
(19, 'Tatsue-ji', '立江寺', 'Komatsushima', 'Tokushima', 4.0, 'Jizo Bosatsu', '1 Tatsue, Komatsushima, Tokushima 773-0017', 'https://commons.wikimedia.org/wiki/File:Tatsuej01.jpg'),
(20, 'Kakurin-ji', '鶴林寺', 'Katsura', 'Tokushima', 16.0, 'Jizo Bosatsu', 'Kakurin, Katsura, Tokushima 771-5177', 'https://commons.wikimedia.org/wiki/File:Kakurinji01.jpg'),
(21, 'Tairyu-ji', '太龍寺', 'Naka', 'Tokushima', 13.0, 'Kokuzo Bosatsu', 'Tairyu, Naka, Tokushima 771-5173', 'https://commons.wikimedia.org/wiki/File:Tairyuji01.jpg'),
(22, 'Byodo-ji', '平等寺', 'Anan', 'Tokushima', 11.0, 'Yakushi Nyorai', '17-1 Byodoji, Anan, Tokushima 779-1510', 'https://commons.wikimedia.org/wiki/File:Byodoji01.jpg'),
(23, 'Yakuo-ji', '薬王寺', 'Minami', 'Tokushima', 19.0, 'Yakushi Nyorai', '19-1 Yakuoji, Minami, Tokushima 779-2306', 'https://commons.wikimedia.org/wiki/File:Yakuoji01.jpg'),
(24, 'Hotsumisaki-ji', '最御崎寺', 'Muroto', 'Kochi', 75.0, 'Kokuzo Bosatsu', 'Muroto, Kochi 781-7101', 'https://commons.wikimedia.org/wiki/File:Hotsumisaki-ji.jpg'),
(25, 'Shinshoji', '津照寺', 'Muroto', 'Kochi', 4.0, 'Jizo Bosatsu', 'Murotoecho, Muroto, Kochi 781-6803', 'https://commons.wikimedia.org/wiki/File:Shinshoji_Muroto.jpg'),
(26, 'Kongochoji', '金剛頂寺', 'Muroto', 'Kochi', 4.0, 'Yakushi Nyorai', 'Murotoecho, Muroto, Kochi 781-6803', 'https://commons.wikimedia.org/wiki/File:Kongochoji01.jpg'),
(27, 'Konomine-ji', '神峯寺', 'Yasuda', 'Kochi', 38.0, 'Juichimen Kannon', 'Konomine, Yasuda, Kochi 781-6410', 'https://commons.wikimedia.org/wiki/File:Konomineji01.jpg'),
(28, 'Dainichi-ji', '大日寺', 'Konan', 'Kochi', 22.0, 'Dainichi Nyorai', 'Dainichi, Konan, Kochi 781-5222', 'https://commons.wikimedia.org/wiki/File:Dainichiji_Konan.jpg'),
(29, 'Kokubun-ji', '国分寺', 'Nankoku', 'Kochi', 8.0, 'Amida Nyorai', 'Kokufucho, Nankoku, Kochi 783-0053', 'https://commons.wikimedia.org/wiki/File:Kokubunji_Kochi.jpg'),
(30, 'Zenraku-ji', '善楽寺', 'Kochi', 'Kochi', 4.0, 'Amida Nyorai', 'Ichinomiya, Kochi 781-8131', 'https://commons.wikimedia.org/wiki/File:Zenrakuji01.jpg'),
(31, 'Chikurin-ji', '竹林寺', 'Kochi', 'Kochi', 5.0, 'Monju Bosatsu', 'Godaisan, Kochi 781-8125', 'https://commons.wikimedia.org/wiki/File:Chikurinji01.jpg'),
(32, 'Zenjibu-ji', '禅師峰寺', 'Nankoku', 'Kochi', 7.0, 'Juichimen Kannon', 'Mine, Nankoku, Kochi 783-0085', 'https://commons.wikimedia.org/wiki/File:Zenjibuj01.jpg'),
(33, 'Sekkei-ji', '雪蹊寺', 'Kochi', 'Kochi', 10.0, 'Yakushi Nyorai', 'Urado, Kochi 781-0262', 'https://commons.wikimedia.org/wiki/File:Sekkeiji01.jpg'),
(34, 'Tanema-ji', '種間寺', 'Harimaya', 'Kochi', 8.0, 'Yakushi Nyorai', 'Sako, Harimaya, Kochi 781-0321', 'https://commons.wikimedia.org/wiki/File:Tanemaji01.jpg'),
(35, 'Kiyotaki-ji', '清瀧寺', 'Tosa', 'Kochi', 15.0, 'Yakushi Nyorai', 'Tosa, Kochi 781-1165', 'https://commons.wikimedia.org/wiki/File:Kiyotakiji01.jpg'),
(36, 'Shoryu-ji', '青龍寺', 'Tosa', 'Kochi', 13.0, 'Fudo Myo-o', 'Tosa, Kochi 781-1104', 'https://commons.wikimedia.org/wiki/File:Shoryuji_Tosa.jpg'),
(37, 'Iwamoto-ji', '岩本寺', 'Shimanto', 'Kochi', 58.0, 'Fudo Myo-o', 'Kure, Shimanto, Kochi 786-0004', 'https://commons.wikimedia.org/wiki/File:Iwamotoji01.jpg'),
(38, 'Kongofuku-ji', '金剛福寺', 'Tosashimizu', 'Kochi', 56.0, 'Senju Kannon', 'Cape Ashizuri, Tosashimizu, Kochi 787-0315', 'https://commons.wikimedia.org/wiki/File:Kongofukuji01.jpg'),
(39, 'Enко-ji', '延光寺', 'Sukumo', 'Kochi', 53.0, 'Yakushi Nyorai', 'Matsuda, Sukumo, Kochi 788-0782', 'https://commons.wikimedia.org/wiki/File:Enkoji_Sukumo.jpg'),
(40, 'Kanjizai-ji', '観自在寺', 'Ainan', 'Ehime', 40.0, 'Amida Nyorai', 'Hirota, Ainan, Ehime 798-4707', 'https://commons.wikimedia.org/wiki/File:Kanjizaiji01.jpg'),
(41, 'Ryuko-ji', '龍光寺', 'Uwajima', 'Ehime', 30.0, 'Senju Kannon', 'Mitsu, Uwajima, Ehime 798-0114', 'https://commons.wikimedia.org/wiki/File:Ryukoji_Uwajima.jpg'),
(42, 'Butsumoku-ji', '仏木寺', 'Uwajima', 'Ehime', 4.0, 'Dainichi Nyorai', 'Kita, Uwajima, Ehime 798-1101', 'https://commons.wikimedia.org/wiki/File:Butsumokuji01.jpg'),
(43, 'Meiseki-ji', '明石寺', 'Seiyo', 'Ehime', 18.0, 'Senju Kannon', 'Uwa, Seiyo, Ehime 797-8501', 'https://commons.wikimedia.org/wiki/File:Meisekiji01.jpg'),
(44, 'Daibo-ji', '大寶寺', 'Kuma Kogen', 'Ehime', 55.0, 'Dainichi Nyorai', 'Omogo, Kuma Kogen, Ehime 791-1205', 'https://commons.wikimedia.org/wiki/File:Daiboji01.jpg'),
(45, 'Iwaya-ji', '岩屋寺', 'Kuma Kogen', 'Ehime', 8.0, 'Fudo Myo-o', 'Omogo, Kuma Kogen, Ehime 791-1220', 'https://commons.wikimedia.org/wiki/File:Iwayaji01.jpg'),
(46, 'Joruri-ji', '浄瑠璃寺', 'Matsuyama', 'Ehime', 35.0, 'Yakushi Nyorai', 'Joruri, Matsuyama, Ehime 791-8023', 'https://commons.wikimedia.org/wiki/File:Joruij01.jpg'),
(47, 'Yasaka-ji', '八坂寺', 'Matsuyama', 'Ehime', 1.0, 'Amida Nyorai', 'Joruri, Matsuyama, Ehime 791-8024', 'https://commons.wikimedia.org/wiki/File:Yasakaji_Matsuyama.jpg'),
(48, 'Sairin-ji', '西林寺', 'Matsuyama', 'Ehime', 4.0, 'Juichimen Kannon', 'Kita, Matsuyama, Ehime 799-2661', 'https://commons.wikimedia.org/wiki/File:Saiirinji01.jpg'),
(49, 'Jodo-ji', '浄土寺', 'Matsuyama', 'Ehime', 3.0, 'Shakyamuni Buddha', 'Ishite, Matsuyama, Ehime 791-8036', 'https://commons.wikimedia.org/wiki/File:Jodoji_Matsuyama.jpg'),
(50, 'Hanta-ji', '繁多寺', 'Matsuyama', 'Ehime', 2.0, 'Yakushi Nyorai', 'Hanta, Matsuyama, Ehime 791-8034', 'https://commons.wikimedia.org/wiki/File:Hantaji01.jpg'),
(51, 'Ishite-ji', '石手寺', 'Matsuyama', 'Ehime', 3.0, 'Yakushi Nyorai', '2-9-21 Ishite, Matsuyama, Ehime 790-0852', 'https://commons.wikimedia.org/wiki/File:Ishiteji01.jpg'),
(52, 'Taizan-ji', '太山寺', 'Matsuyama', 'Ehime', 8.0, 'Juichimen Kannon', 'Taizan, Matsuyama, Ehime 791-8068', 'https://commons.wikimedia.org/wiki/File:Taizanji01.jpg'),
(53, 'Enmyo-ji', '円明寺', 'Matsuyama', 'Ehime', 4.0, 'Amida Nyorai', 'Wakamatsu, Matsuyama, Ehime 791-8066', 'https://commons.wikimedia.org/wiki/File:Enmyoji_Matsuyama.jpg'),
(54, 'Enmei-ji', '延命寺', 'Imabari', 'Ehime', 30.0, 'Fudo Myo-o', 'Emei, Imabari, Ehime 799-1101', 'https://commons.wikimedia.org/wiki/File:Enmeiji_Imabari.jpg'),
(55, 'Nankoin', '南光坊', 'Imabari', 'Ehime', 2.0, 'Dainichi Nyorai', 'Bojo, Imabari, Ehime 794-0001', 'https://commons.wikimedia.org/wiki/File:Nankoin01.jpg'),
(56, 'Taizan-ji', '泰山寺', 'Imabari', 'Ehime', 3.0, 'Jizo Bosatsu', 'Taizan, Imabari, Ehime 794-0113', 'https://commons.wikimedia.org/wiki/File:Taizanji_Imabari.jpg'),
(57, 'Eifuku-ji', '栄福寺', 'Imabari', 'Ehime', 3.0, 'Amida Nyorai', 'Eifuku, Imabari, Ehime 799-1101', 'https://commons.wikimedia.org/wiki/File:Eifukuji01.jpg'),
(58, 'Senyu-ji', '仙遊寺', 'Imabari', 'Ehime', 3.0, 'Senju Kannon', 'Senyu, Imabari, Ehime 799-1103', 'https://commons.wikimedia.org/wiki/File:Senyuji01.jpg'),
(59, 'Kokubun-ji', '国分寺', 'Imabari', 'Ehime', 6.0, 'Yakushi Nyorai', 'Kokubu, Imabari, Ehime 799-1101', 'https://commons.wikimedia.org/wiki/File:Kokubunji_Ehime.jpg'),
(60, 'Yokomine-ji', '横峯寺', 'Saijo', 'Ehime', 25.0, 'Dainichi Nyorai', 'Koguchi, Saijo, Ehime 793-0214', 'https://commons.wikimedia.org/wiki/File:Yokomineji01.jpg'),
(61, 'Koon-ji', '香園寺', 'Saijo', 'Ehime', 7.0, 'Dainichi Nyorai', 'Kobuchi, Saijo, Ehime 793-0204', 'https://commons.wikimedia.org/wiki/File:Koonji01.jpg'),
(62, 'Hoju-ji', '宝寿寺', 'Saijo', 'Ehime', 2.0, 'Juichimen Kannon', 'Kuboecho, Saijo, Ehime 793-0111', 'https://commons.wikimedia.org/wiki/File:Hojuji01.jpg'),
(63, 'Kichijo-ji', '吉祥寺', 'Saijo', 'Ehime', 1.0, 'Bishamonten', 'Tsubaki, Saijo, Ehime 793-0111', 'https://commons.wikimedia.org/wiki/File:Kichiijoji01.jpg'),
(64, 'Maegami-ji', '前神寺', 'Saijo', 'Ehime', 3.0, 'Amida Nyorai', 'Saijo, Ehime 793-0053', 'https://commons.wikimedia.org/wiki/File:Maegamiji01.jpg'),
(65, 'Sankaku-ji', '三角寺', 'Shikokuchuo', 'Ehime', 25.0, 'Juichimen Kannon', 'Nii, Shikokuchuo, Ehime 799-0901', 'https://commons.wikimedia.org/wiki/File:Sankakuji01.jpg'),
(66, 'Unpen-ji', '雲辺寺', 'Mitoyo', 'Kagawa', 30.0, 'Senju Kannon', 'Toriyama, Mitoyo, Kagawa 769-0901', 'https://commons.wikimedia.org/wiki/File:Unpenji01.jpg'),
(67, 'Daiko-ji', '大興寺', 'Mitoyo', 'Kagawa', 10.0, 'Yakushi Nyorai', 'Yamamoto, Mitoyo, Kagawa 769-0901', 'https://commons.wikimedia.org/wiki/File:Daikoji01.jpg'),
(68, 'Jinne-in', '神恵院', 'Kanonji', 'Kagawa', 12.0, 'Amida Nyorai', 'Kotohiki, Kanonji, Kagawa 768-0061', 'https://commons.wikimedia.org/wiki/File:Jinnein01.jpg'),
(69, 'Kanonji', '観音寺', 'Kanonji', 'Kagawa', 0.1, 'Senju Kannon', 'Kotohiki, Kanonji, Kagawa 768-0061', 'https://commons.wikimedia.org/wiki/File:Kannonji_Kanonji.jpg'),
(70, 'Motoyama-ji', '本山寺', 'Mitoyo', 'Kagawa', 3.0, 'Bato Kannon', 'Honzan, Mitoyo, Kagawa 769-1506', 'https://commons.wikimedia.org/wiki/File:Motoyamaji01.jpg'),
(71, 'Iyadani-ji', '弥谷寺', 'Mitoyo', 'Kagawa', 10.0, 'Senju Kannon', 'Iyadani, Mitoyo, Kagawa 767-0031', 'https://commons.wikimedia.org/wiki/File:Iyadaniji01.jpg'),
(72, 'Mandara-ji', '曼荼羅寺', 'Zentsuji', 'Kagawa', 8.0, 'Dainichi Nyorai', 'Mandara, Zentsuji, Kagawa 765-0071', 'https://commons.wikimedia.org/wiki/File:Mandaraji01.jpg'),
(73, 'Shusshaka-ji', '出釈迦寺', 'Zentsuji', 'Kagawa', 1.0, 'Shakyamuni Buddha', 'Yoshiwara, Zentsuji, Kagawa 765-0073', 'https://commons.wikimedia.org/wiki/File:Shusshakaji01.jpg'),
(74, 'Koyama-ji', '甲山寺', 'Zentsuji', 'Kagawa', 2.0, 'Yakushi Nyorai', 'Yoshiwara, Zentsuji, Kagawa 765-0073', 'https://commons.wikimedia.org/wiki/File:Koyamaji01.jpg'),
(75, 'Zentsu-ji', '善通寺', 'Zentsuji', 'Kagawa', 1.0, 'Yakushi Nyorai', '3-3-1 Zentsuji, Zentsuji, Kagawa 765-8612', 'https://commons.wikimedia.org/wiki/File:Zentsuji01.jpg'),
(76, 'Konzo-ji', '金倉寺', 'Zentsuji', 'Kagawa', 3.0, 'Yakushi Nyorai', 'Konzo, Zentsuji, Kagawa 765-0061', 'https://commons.wikimedia.org/wiki/File:Konzoji01.jpg'),
(77, 'Doryu-ji', '道隆寺', 'Marugame', 'Kagawa', 6.0, 'Yakushi Nyorai', 'Nishikata, Marugame, Kagawa 763-0076', 'https://commons.wikimedia.org/wiki/File:Doryuji01.jpg'),
(78, 'Gosho-ji', '郷照寺', 'Utazu', 'Kagawa', 6.0, 'Amida Nyorai', 'Utazu, Kagawa 769-0210', 'https://commons.wikimedia.org/wiki/File:Goshoji01.jpg'),
(79, 'Tenno-ji', '天皇寺', 'Sakaide', 'Kagawa', 8.0, 'Yakushi Nyorai', 'Shiromine, Sakaide, Kagawa 762-0016', 'https://commons.wikimedia.org/wiki/File:Tennoji_Sakaide.jpg'),
(80, 'Kokubun-ji', '国分寺', 'Takamatsu', 'Kagawa', 6.0, 'Senju Kannon', 'Kokubucho, Takamatsu, Kagawa 769-0102', 'https://commons.wikimedia.org/wiki/File:Kokubunji_Kagawa.jpg'),
(81, 'Shiromine-ji', '白峯寺', 'Sakaide', 'Kagawa', 10.0, 'Senju Kannon', 'Shiromine, Sakaide, Kagawa 762-0016', 'https://commons.wikimedia.org/wiki/File:Shirominej01.jpg'),
(82, 'Negoroji', '根香寺', 'Takamatsu', 'Kagawa', 5.0, 'Senju Kannon', 'Negoroji, Takamatsu, Kagawa 761-8004', 'https://commons.wikimedia.org/wiki/File:Negoroji01.jpg'),
(83, 'Ichinomiya-ji', '一宮寺', 'Takamatsu', 'Kagawa', 12.0, 'Sho Kannon', 'Ichinomiya, Takamatsu, Kagawa 761-8004', 'https://commons.wikimedia.org/wiki/File:Ichinomiyaji01.jpg'),
(84, 'Yashima-ji', '屋島寺', 'Takamatsu', 'Kagawa', 8.0, 'Juichimen Kannon', 'Yashima, Takamatsu, Kagawa 761-0111', 'https://commons.wikimedia.org/wiki/File:Yashimaji01.jpg'),
(85, 'Yakuri-ji', '八栗寺', 'Takamatsu', 'Kagawa', 8.0, 'Sho Kannon', 'Yakuri, Takamatsu, Kagawa 769-0210', 'https://commons.wikimedia.org/wiki/File:Yakuriji01.jpg'),
(86, 'Shido-ji', '志度寺', 'Sanuki', 'Kagawa', 7.0, 'Juichimen Kannon', 'Shido, Sanuki, Kagawa 769-2101', 'https://commons.wikimedia.org/wiki/File:Shidoji01.jpg'),
(87, 'Nagao-ji', '長尾寺', 'Sanuki', 'Kagawa', 5.0, 'Sho Kannon', 'Nagao, Sanuki, Kagawa 769-2306', 'https://commons.wikimedia.org/wiki/File:Nagaoji01.jpg'),
(88, 'Okuboji', '大窪寺', 'Sanuki', 'Kagawa', 14.0, 'Yakushi Nyorai', 'Okubo, Sanuki, Kagawa 769-2306', 'https://commons.wikimedia.org/wiki/File:Okubo-ji_02.jpg');